### ISSUE TITLE
Possible documentation error

### ISSUE THREAD

**Issue by binarynightowl** [Rilufi/coronga#1]
Hello,
I noticed that you were using my covid19-data library in python, so I just stopped by to check out your really neat twitter bot! Looks great! Just wanted to mention that you say to follow the directions on https://pypi.org/project/covid-19/ to change the covid data, but that seems to be a different package than the one that you are using in your project. Just so people following your guide do not get confused I think you meant to link to https://pypi.org/project/covid19-data/ if I am not mistaken. Just wanted to let you know. 
Cheers,
BinaryNightowl

**Comment by Rilufi** [comment]
Omg that's right, thanks for the heads up! I'll fix it right away.
And thanks for the library, I was having a hard time finding a way to get this data, since the cloud server that the bot is hosted don't let my bot explore third-party sites, but your library fixed this issue as I'm allowed to install any Python library.
Cheers,
Rilufi

**Comment by Rilufi** [comment]
> Hello,
> I noticed that you were using my covid19-data library in python, so I just stopped by to check out your really neat twitter bot! Looks great! Just wanted to mention that you say to follow the directions on https://pypi.org/project/covid-19/ to change the covid data, but that seems to be a different package than the one that you are using in your project. Just so people following your guide do not get confused I think you meant to link to https://pypi.org/project/covid19-data/ if I am not mistaken. Just wanted to let you know.
> Cheers,
> BinaryNightowl

Omg that's right, thanks for the heads up! I'll fix it right away.
And thanks for the library, I was having a hard time finding a way to get this data, since the cloud server that the bot is hosted don't let my bot explore third-party sites, but your library fixed this issue as I'm allowed to install any Python library.
Cheers,
Rilufi

**Comment by Rilufi** [comment]
> Hello,
> I noticed that you were using my covid19-data library in python, so I just stopped by to check out your really neat twitter bot! Looks great! Just wanted to mention that you say to follow the directions on https://pypi.org/project/covid-19/ to change the covid data, but that seems to be a different package than the one that you are using in your project. Just so people following your guide do not get confused I think you meant to link to https://pypi.org/project/covid19-data/ if I am not mistaken. Just wanted to let you know.
> Cheers,
> BinaryNightowl

Omg that's right, thanks for the heads up! I'll fix it right away.
And thanks for the library, I was having a hard time finding a way to get this data, since the cloud server that the bot is hosted doesn't let my bot explore third-party sites, but your library fixed this issue as I'm allowed to install any Python library.
Cheers,
Rilufi
